package visao;

import javax.swing.ImageIcon;

/**
 *
 * @author osmar
 */
public class FrmImagem extends javax.swing.JFrame {

    /**
     * Creates new form FrmImagem
     */
    public FrmImagem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLbImagem2 = new javax.swing.JLabel();
        jBtCarregar = new javax.swing.JButton();
        jBtFechar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JLbImagem1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Exemplo de carregamento de imagem");

        jLbImagem2.setText("Imagem2");

        jBtCarregar.setText("Carregar imagem");
        jBtCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCarregarActionPerformed(evt);
            }
        });

        jBtFechar.setText("Fechar");
        jBtFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtFecharActionPerformed(evt);
            }
        });

        jLabel1.setText("Imagem pré-carregada no JLabel");

        JLbImagem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem1.jpg"))); // NOI18N
        JLbImagem1.setText("Imagem1");

        jLabel4.setText("Imagem carregada durante a execução no JLabel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(JLbImagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLbImagem2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtCarregar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jBtFechar)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLbImagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLbImagem2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jBtCarregar)))))
                .addGap(9, 9, 9)
                .addComponent(jBtFechar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCarregarActionPerformed
        // TODO add your handling code here:
        //Caminho da imagem
        String localImagem = "/imagem2.jpg";
        //Cria o objeto imagem
        ImageIcon imagem = new ImageIcon(getClass().getResource(localImagem));
        //Coloca a imagem no JLabel.
        jLbImagem2.setIcon(imagem);
    }//GEN-LAST:event_jBtCarregarActionPerformed

    private void jBtFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtFecharActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jBtFecharActionPerformed
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLbImagem1;
    private javax.swing.JButton jBtCarregar;
    private javax.swing.JButton jBtFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLbImagem2;
    // End of variables declaration//GEN-END:variables
}
